<?php

use Illuminate\Database\Seeder;

class SurveySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $surveys = [
            ['display_order' => 1, 'category_id' => 1, 'question' => 'Disfruto haciendo feliz a otras personas.'],
            ['display_order' => 2, 'category_id' => 2, 'question' => 'Las relaciones íntimas son importantes para mí.'],
            ['display_order' => 3, 'category_id' => 3, 'question' => 'Disfruto estar en bibliotecas y museos.'],
            ['display_order' => 4, 'category_id' => 4, 'question' => 'Admiro la excelencia y habilidad de los grandes maestros, artistas y científicos.'],
            ['display_order' => 5, 'category_id' => 5, 'question' => 'Me es fácil seguir una dieta al pie de la letra.'],
            ['display_order' => 6, 'category_id' => 6, 'question' => 'Evalúo todos los pros y los contras antes de tomar decisiones.'],
            ['display_order' => 7, 'category_id' => 7, 'question' => 'Me caracterizo por tener pensamientos originales y creativos.'],
            ['display_order' => 8, 'category_id' => 8, 'question' => 'Cuando veo algo nuevo, siempre me detengo a investigar.'],
            ['display_order' => 9, 'category_id' => 9, 'question' => 'Cada día lo comienzo lleno de energía positiva.'],
            ['display_order' => 10, 'category_id' => 10, 'question' => 'Aunque algo no me salgan bien, sé que la situación va a mejorar en el futuro.'],
            ['display_order' => 11, 'category_id' => 11, 'question' => 'Aparte del mundo material, creo en la existencia de un mundo espiritual.'],
            ['display_order' => 12, 'category_id' => 12, 'question' => 'Diariamente me siento agradecido por todas las cosas buenas que me pasan en la vida.'],
            ['display_order' => 13, 'category_id' => 13, 'question' => 'Nunca prometo algo que no vaya a cumplir.'],
            ['display_order' => 14, 'category_id' => 14, 'question' => 'Cuando se trata de ropa, joyas, relojes, calzado, fragancias, etc., nunca compro artículos de lujo costosos.'],
            ['display_order' => 15, 'category_id' => 15, 'question' => 'A las personas les gusta compartir conmigo por mi sentido del humor, siempre soy el alma de las fiestas.'],
            ['display_order' => 16, 'category_id' => 16, 'question' => 'No me importa que mis amigos me vean hablando con personas ricas o pobres, o de cualquier orientación sexual.'],
            ['display_order' => 17, 'category_id' => 17, 'question' => 'Me es fácil entender y controlar mis estados emocionales.'],
            ['display_order' => 18, 'category_id' => 18, 'question' => 'Cuando trabajo como parte de un grupo, se me hace muy fácil destacar y tomar un rol de liderazgo.'],
            ['display_order' => 19, 'category_id' => 19, 'question' => 'Cuando alguien me lastima, mi lema es perdonar y olvidar.'],
            ['display_order' => 20, 'category_id' => 20, 'question' => 'Continúo haciendo tareas difíciles incluso cuando otros se han dado por vencidos.'],
            ['display_order' => 21, 'category_id' => 21, 'question' => 'La gente me busca para que los aconseje cuando tienen problemas en el trabajo o en su vida personal.'],
            ['display_order' => 22, 'category_id' => 22, 'question' => 'Cuando estoy en una discusión acalorada, evito decir cosas de las que me pueda arrepentir en el futuro.'],
            ['display_order' => 23, 'category_id' => 23, 'question' => 'Siempre sigo las instrucciones y colaboro cuando trabajo en equipo, así no esté de acuerdo con el líder del grupo.'],
            ['display_order' => 24, 'category_id' => 24, 'question' => 'Arriesgaría mi vida por salvar a una persona que se encuentre en peligro.'],
            ['display_order' => 25, 'category_id' => 1, 'question' => 'Siempre me esfuerzo por ayudar a los demás.'],
            ['display_order' => 26, 'category_id' => 2, 'question' => 'Me es fácil dar y recibir cariño.'],
            ['display_order' => 27, 'category_id' => 3, 'question' => 'Me apasiona aprender cosas nuevas.'],
            ['display_order' => 28, 'category_id' => 4, 'question' => 'Frecuentemente noto la belleza natural del mundo que me rodea.'],
            ['display_order' => 29, 'category_id' => 5, 'question' => 'No suelo comprar cosas que sé que no necesito.'],
            ['display_order' => 30, 'category_id' => 6, 'question' => 'Mi proceso de toma de decisiones es siempre deliberado, sistemático y lógico.'],
            ['display_order' => 31, 'category_id' => 7, 'question' => 'Me desempeñaría muy bien en un trabajo donde se necesite imaginación como en el área de publicidad y mercadeo.'],
            ['display_order' => 32, 'category_id' => 8, 'question' => 'Me gusta estudiar objetos que son desconcertantes e inusuales.'],
            ['display_order' => 33, 'category_id' => 9, 'question' => 'Cada día es una aventura que vivo a plenitud.'],
            ['display_order' => 34, 'category_id' => 10, 'question' => 'Estoy seguro de que voy a tener una vida llana de grandes éxitos.'],
            ['display_order' => 35, 'category_id' => 11, 'question' => 'Frecuentemente atiendo a prácticas religiosas.'],
            ['display_order' => 36, 'category_id' => 12, 'question' => 'Me siento agradecido y usualmente pienso en todas las personas que hacen que mi vida sea más sencilla.'],
            ['display_order' => 37, 'category_id' => 13, 'question' => 'Siempre actúo de una forma genuina y autentica, nunca ando con mentiras ni falsedades.'],
            ['display_order' => 38, 'category_id' => 14, 'question' => 'Me siento muy incómodo cuando la gente me trata como si yo fuera importante o especial.'],
            ['display_order' => 39, 'category_id' => 15, 'question' => 'No importa dónde esté, con quién esté o cómo me sienta, usualmente me divierto y me río con mucha facilidad.'],
            ['display_order' => 40, 'category_id' => 16, 'question' => 'Si tuviera que adoptar, adoptaría un niño de una raza muy diferente a la mía.'],
            ['display_order' => 41, 'category_id' => 17, 'question' => 'Siempre sé cómo se están sintiendo las personas, especialmente en situaciones sociales complejas.'],
            ['display_order' => 42, 'category_id' => 18, 'question' => 'Durante mis estudios y en mi trabajo, he sido promovido a posiciones de liderazgo repetidas veces.'],
            ['display_order' => 43, 'category_id' => 19, 'question' => 'Cuando me siento ofendido por otras personas, nunca busco vengarme ni hablar mal de ellas.'],
            ['display_order' => 44, 'category_id' => 20, 'question' => 'Cuanto más difícil es una tarea, más determinado me siento a terminarla.'],
            ['display_order' => 45, 'category_id' => 21, 'question' => 'Me es fácil ver el trasfondo de las situaciones, por lo que comprendo fácilmente como abordar los problemas.'],
            ['display_order' => 46, 'category_id' => 22, 'question' => 'Me considero una persona prudente, por lo cual siempre actúo con cuidado, precaución y buen juicio.'],
            ['display_order' => 47, 'category_id' => 23, 'question' => 'Cuando trabajo en equipo, siempre trato de incluir a los otros miembros porque valoro sus contribuciones.'],
            ['display_order' => 48, 'category_id' => 24, 'question' => 'Con gusto sacrificaría la seguridad y la conveniencia de mi vida para lograr un objetivo que sea noble y digno.'],
            ['display_order' => 49, 'category_id' => 1, 'question' => 'Siempre soy amable con las personas.'],
            ['display_order' => 50, 'category_id' => 2, 'question' => 'Siento un profundo afecto y apego por muchas personas en mi vida.'],
            ['display_order' => 51, 'category_id' => 3, 'question' => 'Siempre he sido un buen estudiante.'],
            ['display_order' => 52, 'category_id' => 4, 'question' => 'Las cosas bien hechas me generan sentimientos de placer y bienestar.'],
            ['display_order' => 53, 'category_id' => 5, 'question' => 'Soy bueno resistiendo tentaciones.'],
            ['display_order' => 54, 'category_id' => 6, 'question' => 'Mis instintos y emociones no interfieren en mi pensamiento crítico, nunca saco conclusiones prematuras.'],
            ['display_order' => 55, 'category_id' => 7, 'question' => 'Me es fácil encontrar la forma óptima de hacer las cosas.'],
            ['display_order' => 56, 'category_id' => 8, 'question' => 'Me gusta investigar y aprender sobre temas interesantes.'],
            ['display_order' => 57, 'category_id' => 9, 'question' => 'Me gusta mi trabajo y lo hago con entusiasmo y alegría.'],
            ['display_order' => 58, 'category_id' => 10, 'question' => 'He afrontado adversidades, pero nunca he perdido la esperanza.'],
            ['display_order' => 59, 'category_id' => 11, 'question' => 'La espiritualidad dirige mi conducta y me hace una mejor persona.'],
            ['display_order' => 60, 'category_id' => 12, 'question' => 'Siempre me aseguro de tomarme el tiempo necesario para expresar agradecimiento por los favores recibidos.'],
            ['display_order' => 61, 'category_id' => 13, 'question' => 'Siempre digo la verdad, así no le guste a otras personas.'],
            ['display_order' => 62, 'category_id' => 14, 'question' => 'Soy una persona humilde, no siento orgullo cuando hago las cosas mejor que los demás.'],
            ['display_order' => 63, 'category_id' => 15, 'question' => 'No pierdo mi sentido del humor cuando estoy teniendo un mal día.'],
            ['display_order' => 64, 'category_id' => 16, 'question' => 'No tengo preferencia que mi superior en el trabajo sea un hombre o una mujer.'],
            ['display_order' => 65, 'category_id' => 17, 'question' => 'Soy bueno percibiendo los sentimientos y los estados de ánimo de otras personas.'],
            ['display_order' => 66, 'category_id' => 18, 'question' => 'Mis compañeros me reconocen como un buen líder.'],
            ['display_order' => 67, 'category_id' => 19, 'question' => 'Para mí, el perdón no es un acto ocasional sino una actitud frecuente.'],
            ['display_order' => 68, 'category_id' => 20, 'question' => 'Me mantengo motivado incluso en actividades que se extienden por meses o años.'],
            ['display_order' => 69, 'category_id' => 21, 'question' => 'Mis amigos me consideran una persona sabia.'],
            ['display_order' => 70, 'category_id' => 22, 'question' => 'Siempre pienso muy bien todo cuanto voy a hacer antes de tomar decisiones y antes de actuar.'],
            ['display_order' => 71, 'category_id' => 23, 'question' => 'Me gustan más los proyectos en equipo que los proyectos individuales.'],
            ['display_order' => 72, 'category_id' => 24, 'question' => 'Nunca me dejo intimidar por las amenazas de un brabucón (bully), así sepa que voy a ser golpeado.'],
            ['display_order' => 73, 'category_id' => 1, 'question' => 'Soy de carácter alegre y amistoso.'],
            ['display_order' => 74, 'category_id' => 2, 'question' => 'Soy muy cercano a mis familiares y tengo buenas relaciones con todos ellos.'],
            ['display_order' => 75, 'category_id' => 3, 'question' => 'Tengo amplio conocimiento sobre cultura general.'],
            ['display_order' => 76, 'category_id' => 4, 'question' => 'Me deleitan las obras de arte (arquitectura, escultura, música, pintura y literatura).'],
            ['display_order' => 77, 'category_id' => 5, 'question' => 'Soy una persona con mucha disciplina.'],
            ['display_order' => 78, 'category_id' => 6, 'question' => 'Soy bueno tomando decisiones acertadas y llegando a conclusiones razonables.'],
            ['display_order' => 79, 'category_id' => 7, 'question' => 'Soy bueno desarrollando ideas novedosas y útiles.'],
            ['display_order' => 80, 'category_id' => 8, 'question' => 'Tengo una mente muy curiosa.'],
            ['display_order' => 81, 'category_id' => 9, 'question' => 'Todas mis actividades las hago con ganas y con buena actitud.'],
            ['display_order' => 82, 'category_id' => 10, 'question' => 'Inicio cada día con la certeza de que me van a pasar muchas cosas buenas.'],
            ['display_order' => 83, 'category_id' => 11, 'question' => 'Siento la presencia de Dios en mi vida muy frecuentemente.'],
            ['display_order' => 84, 'category_id' => 12, 'question' => 'Siento un gran agradecimiento por las cosas pequeñas y grandes de la vida.'],
            ['display_order' => 85, 'category_id' => 13, 'question' => 'Soy honesto, no cometo ni tolero que otras personas cometan actos de corrupción.'],
            ['display_order' => 86, 'category_id' => 14, 'question' => 'Tengo una visión modesta de mi importancia personal.'],
            ['display_order' => 87, 'category_id' => 15, 'question' => 'Tengo la capacidad de divertirme y reírme en una amplia variedad de situaciones.'],
            ['display_order' => 88, 'category_id' => 16, 'question' => 'Siempre trato a todas las personas con igualdad y justicia.'],
            ['display_order' => 89, 'category_id' => 17, 'question' => 'Tengo facilidad para adaptarme a grupos conformados por personas desconocidas.'],
            ['display_order' => 90, 'category_id' => 18, 'question' => 'Soy bueno motivando a grupos de personas para que alcancen sus objetivos.'],
            ['display_order' => 91, 'category_id' => 19, 'question' => 'Me es fácil perdonar las malas obras de familiares, amigos y compañeros de trabajo.'],
            ['display_order' => 92, 'category_id' => 20, 'question' => 'Sigo invirtiendo tiempo y esfuerzo en ideas y proyectos que requieren de mucho tiempo y paciencia.'],
            ['display_order' => 93, 'category_id' => 21, 'question' => 'Siempre examino las situaciones considerando todos los puntos de vista y toda la información relevante.'],
            ['display_order' => 94, 'category_id' => 22, 'question' => 'Soy bueno evitando situaciones que se pueden salir de control.'],
            ['display_order' => 95, 'category_id' => 23, 'question' => 'Prefiero recibir un reconocimiento como parte de un equipo, a un premio por un trabajo que haya hecho individualmente.'],
            ['display_order' => 96, 'category_id' => 24, 'question' => 'Nunca retrocedo ante los desafíos, las dificultades o el dolor físico.'],
            ['display_order' => 97, 'category_id' => 1, 'question' => 'Trato a las personas con mucho afecto.'],
            ['display_order' => 98, 'category_id' => 2, 'question' => 'Soy una persona amorosa.'],
            ['display_order' => 99, 'category_id' => 3, 'question' => 'Tengo una gran colección de libros en la casa.'],
            ['display_order' => 100, 'category_id' => 4, 'question' => 'Mi casa está muy bien decorada y la mantengo siempre en orden.'],
            ['display_order' => 101, 'category_id' => 5, 'question' => 'Tengo fuerza de voluntad.'],
            ['display_order' => 102, 'category_id' => 6, 'question' => 'Soy flexible y puedo cambiar de opinión al recibir nueva evidencia.'],
            ['display_order' => 103, 'category_id' => 7, 'question' => 'Tengo una gran capacidad para inventar objetos, técnicas o procesos innovadores.'],
            ['display_order' => 104, 'category_id' => 8, 'question' => 'Usualmente, siento un intenso deseo de saber cómo funcionan las cosas.'],
            ['display_order' => 105, 'category_id' => 9, 'question' => 'Siempre me siento vivo y lleno de energía.'],
            ['display_order' => 106, 'category_id' => 10, 'question' => 'Tengo la esperanza de que voy a alcanzar todas las metas y objetivos que me he trazado para este año.'],
            ['display_order' => 107, 'category_id' => 11, 'question' => 'Soy una persona de fe inquebrantable.'],
            ['display_order' => 108, 'category_id' => 12, 'question' => 'Usualmente busco maneras originales para mostrar mi agradecimiento a familiares y amigos.'],
            ['display_order' => 109, 'category_id' => 13, 'question' => 'Soy una persona transparente, no aparento lo que no es, lo que la gente ve es como realmente soy.'],
            ['display_order' => 110, 'category_id' => 14, 'question' => 'Valoro a los demás tanto como a mí mismo, sabiendo que todos tenemos limitaciones y debilidades.'],
            ['display_order' => 111, 'category_id' => 15, 'question' => 'Usualmente trato de decir algo cómico cuando estoy en situaciones tensas.'],
            ['display_order' => 112, 'category_id' => 16, 'question' => 'Sin distinción, le doy a todas las personas las mismas oportunidades.'],
            ['display_order' => 113, 'category_id' => 17, 'question' => 'Tengo un buen dominio de las reglas sociales, lo cual me permite encajar bien con otras personas.'],
            ['display_order' => 114, 'category_id' => 18, 'question' => 'Soy bueno organizando actividades grupales y velando porque las actividades se cumplan rápida y eficazmente.'],
            ['display_order' => 115, 'category_id' => 19, 'question' => 'Soy de las personas que no guardan rencor por las ofensas del pasado.'],
            ['display_order' => 116, 'category_id' => 20, 'question' => 'Una vez que decido hacer algo, no me detengo hasta alcanzar la meta.'],
            ['display_order' => 117, 'category_id' => 21, 'question' => 'Soy bueno juzgando correctamente los asuntos relacionados a las contradicciones de la vida y la conducta de las personas.'],
            ['display_order' => 118, 'category_id' => 22, 'question' => 'Soy una persona cautelosa que evita tomar riesgos innecesarios.'],
            ['display_order' => 119, 'category_id' => 23, 'question' => 'Soy de las personas que se esfuerza más cuando trabaja como parte de un equipo que cuando trabaja individualmente.'],
            ['display_order' => 120, 'category_id' => 24, 'question' => 'Siempre hago lo correcto y digo lo que pienso, aunque mi postura no sea popular.']
        ];

        for( $i = 0; $i < count( $surveys ); $i ++ ){
            DB::table('surveys')->insert([
                'display_order' =>  $surveys[$i]['display_order'],
                'category_id'   =>  $surveys[$i]['category_id'],
                'question'      =>  $surveys[$i]['question'],
                'status'        =>  1,
                'memo'          =>  '',
                'created_at'    =>  date('Y-m-d H:i:s'),
                'updated_at'    =>  date('Y-m-d H:i:s')
            ]);
        }
    }
}
