version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trainingapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-njlh2t8cgath"
s3_prefix = "trainingapp"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
